### ISSUE TITLE
Unable to detect game instance

### ISSUE THREAD

**Issue by ZachHandley** [mixxorz/GarageBard#17]
Hey there,

On Mac OSX Monterey 12.2.1, accessibility settings enabled, can't find the game process - it does work however

Any help would be appreciated
- Zach

**Comment by mixxorz** [comment]
Hiya. Thanks for reporting!

What computer do you have? M1 or Intel?

Are you using the stock launcher or XIV on Mac?

With the game running, could you open up Activity Monitor and find what the game's process name is? It should be the one eating up a lot of CPU usage... A screenshot would help too if that's OK.

**Comment by ZachHandley** [comment]
Intel, Stock launcher, yes definitely :) 

<img width="955" alt="image" src="https://user-images.githubusercontent.com/16495679/159147842-ee0617e6-a84a-4d01-a43c-520824a95255.png">

**Comment by mixxorz** [comment]
Thanks for the info! I've surmised that this is because GarageBard doesn't know how to detect the stock launcher. 🙃 

A bit weird for sure, but straightforward enough to fix.

Unfortunately, I can't quite reproduce this right now as the stock launcher no longer works on macOS 12.3. So don't update!! Or if you do, switch to XIV on Mac.

**Comment by mixxorz** [comment]
Just as I say that, I was able to get the game running with the stock launcher.

Do you mind testing version [1.1.1](https://github.com/mixxorz/GarageBard/releases/tag/1.1.1) please and see if it's working for you?

**Comment by ZachHandley** [comment]
I'll test it now! :)

Works! I really appreciate this! I was looking for a mac version for a long time and this is a gorgeous UI, .app file instead of code, responsive time, amazing. Thanks so much :)

**Comment by mixxorz** [comment]
I'm glad it's working and you're finding it useful! ☺️
